@startuml
!pragma teoz true
hide footbox
title Modificación de Proveedores

actor "admin:Administrador" as admin
participant "gc:FarmaciaControlador" as gc
participant "catProv:<<Singleton>>\nCatalogoProveedores" as catProv
participant "listaProv[i]:Drogueria" as arrayProv
participant "provEncontrado:Drogueria" as provObj
participant "DireccionDrog:Direccion" as dirObj

' =================================================================
' INICIO
' =================================================================
' El admin envía los datos desglosados (incluyendo los de la dirección)
admin -> gc : modificarDrogueria(nombre : String, email : String, tel : String, calle : String, num : INT, loc : String, CUIT : INT, canalPreferido : String)
activate gc

' -----------------------------------------------------------------
' PASO 1: BUSCAR EL PROVEEDOR
' -----------------------------------------------------------------
gc -> catProv : buscarProveedor(nombre)
activate catProv

loop Para cada Drogueria en listaProv
    catProv -> arrayProv : getCUIT()
    activate arrayProv
    arrayProv --> catProv : << CUITactual : String >>
    deactivate arrayProv
end

catProv --> gc : << DrogEncontrada : Drogueria >>
deactivate catProv

' -----------------------------------------------------------------
' PASO 2: MODIFICACIÓN
' -----------------------------------------------------------------
alt No se encontró la Drogueria
    gc --> admin : "Error: El proveedor no existe"
else Se encontró la Drogueria
    gc -> provObj : setEmail(email : String)
    activate provObj
    provObj --> gc : <<NULL>>
    deactivate provObj

    gc -> provObj : setNumTel(tel : String)
    activate provObj
    provObj --> gc : <<NULL>>
    deactivate provObj

    note right of gc
        Accedemos al objeto compuesto
        para editar sus campos
    end note
    
    gc -> provObj : getDireccion()
    activate provObj
    provObj --> gc : << DireccionDrog : Direccion>>
    deactivate provObj
    
    gc -> dirObj : setCalle(calle : String)
    activate dirObj
    dirObj --> gc : <<NULL>>
    deactivate dirObj
    
    gc -> dirObj : setNumero(num : INT)
    activate dirObj
    dirObj --> gc : <<NULL>>
    deactivate dirObj
    
    gc -> dirObj : setLocalidad(loc : String)
    activate dirObj
    dirObj --> gc : <<NULL>>
    deactivate dirObj

    ' C) MODIFICAR ATRIBUTOS PROPIOS (Drogueria)
    gc -> provObj : setCanalPreferido(canalPreferido : String)
    activate provObj
    provObj --> gc : <<NULL>>
    deactivate provObj
    
    gc --> admin : "Éxito: Proveedor modificado correctamente."
    deactivate gc
end
@enduml