@startuml
title Pago

hide footbox

actor "Empleado" as emp
participant "Interfaz: NegocioControlador" as NegCtrl
participant "Venta: objVenta" as venta
participant "Cliente: objCliente" as cli
participant "Pago: objPago" as pago
participant "Interfaz : ServicioPagos" as srvPagos
participant "DetalleVenta: det" as det
participant "Medicamento: med" as med
participant "Ticketera" as printer
participant "Interfaz : ServicioCorreos" as mailer

emp -> NegCtrl : iniciarCobro()
activate NegCtrl

loop Mientras estado venta == PENDIENTE
    
    emp -> NegCtrl : seleccionarMedioPago(medio: String, cuotas: Int)
    
    NegCtrl -> venta : calcularMontoFinal(medio, cuotas)
    activate venta
    
        note right of venta
            Aplica recargo (cuotas > 3)
            o descuento (Efectivo + Frecuente)
        end note
    
    venta --> NegCtrl : << montoFinal : Float >>
    deactivate venta

    alt medio == "Cuenta Corriente"
        
        NegCtrl -> venta : getCliente()
        activate venta
        venta --> NegCtrl : << objCliente >>
        deactivate venta
        
        NegCtrl -> cli : esFrecuente()
        activate cli
        cli --> NegCtrl : << esFrecuente : Boolean >>
        deactivate cli
        
        NegCtrl -> cli : getSaldoDisponible()
        activate cli
        cli --> NegCtrl : << saldo : Float >>
        deactivate cli

        alt esFrecuente AND saldo >= montoFinal
            NegCtrl -> cli : actualizarSaldo(-montoFinal)
            activate cli
            cli --> NegCtrl : <<NULL>>
            deactivate cli
            
            NegCtrl -> venta : registrarPago(montoFinal, "CtaCte")
            activate venta
                    venta -> pago ** : create(numTransaccion, tipoPago, montoFinal)
                    activate pago
                    pago --> venta : << objPago >>
                    venta -> pago : setNumTransaccion(Pago.asignarNumTransaccion())
                    venta -> pago : setEstado("APROBADO")
                    venta -> pago : setMonto(montoFinal)
            venta --> NegCtrl : <<NULL>>
            deactivate venta
            
            NegCtrl -> venta : setEstado("CONFIRMADA")
            activate venta
            deactivate venta

        else Rechazo Interno
            NegCtrl --> emp : <<Error: Saldo Insuficiente / No Frecuente>>
        end

    else Medio Externo (Tarjeta/Efectivo)
        
        NegCtrl -> venta : validarReglasPago(medio, cuotas)
        activate venta
        venta --> NegCtrl : << esValido : Boolean >>
        deactivate venta
        
        alt esValido == true
            NegCtrl -> srvPagos : iniciarTransaccion(montoFinal, medio, cuotas)
            activate srvPagos
            srvPagos --> NegCtrl : << estado : String >>
            deactivate srvPagos
            
            alt estado == "APROBADO"
                NegCtrl -> venta : registrarPago(montoFinal, medio)
                activate venta
                    venta -> pago ** : create(numTransaccion, tipoPago, montoFinal)
                    activate pago
                    pago --> venta : << objPago >>
                    venta -> pago : setNumTransaccion(Pago.asignarNumTransaccion())
                    venta -> pago : setEstado("APROBADO")
                    venta -> pago : setMonto(montoFinal)
                    deactivate pago
                venta --> NegCtrl : <<NULL>>
                deactivate venta
                
                NegCtrl -> venta : setEstado("CONFIRMADA")
                activate venta
                deactivate venta
            else RECHAZADA
                NegCtrl --> emp : <<Error: Pago Rechazado>>
            end
        else Reglas Violadas
            NegCtrl --> emp : <<Error: Medio no permitido (Ej: OS en cuotas)>>
        end
    end

    NegCtrl -> venta : getEstado()
    activate venta
    venta --> NegCtrl : << estadoVenta : String >>
    deactivate venta

    alt estadoVenta == "CONFIRMADA"
        
        NegCtrl -> venta : actualizarStock()
        activate venta
            loop detalles
                venta -> det : actualizarCantidadStock()
                activate det
                det -> med : actualizarStock(-cantidad)
                activate med
                med --> det : <<NULL>>
                deactivate med
                det --> venta : <<NULL>>
                deactivate det
            end
        venta --> NegCtrl : <<NULL>>
        deactivate venta

        NegCtrl -> printer : imprimirTicket(venta)
        activate printer
        printer --> NegCtrl : << impreso : Boolean >>
        deactivate printer
        
        opt impreso == false
            NegCtrl -> cli : getEmail()
            activate cli
            cli --> NegCtrl : << email : String >>
            deactivate cli
            NegCtrl -> mailer : enviarTicket(venta, email)
            activate mailer
            deactivate mailer
        end

        NegCtrl --> emp : <<NULL>>
        
    else Venta No Confirmada
        opt Cancelar Operación
            emp -> NegCtrl : cancelarVenta()
            NegCtrl -> venta : setEstado("CANCELADA")
        end
    end
end

NegCtrl --> emp : <<NULL>>
deactivate NegCtrl
@enduml