@startuml
title Venta Sin Receta (Con Tipos de Dato)

hide footbox

actor "Empleado" as emp
participant "Interfaz: NegCtrl" as NegCtrl
participant "List<Cliente>: CatalogoClientes" as listaCli
participant "Cliente: objCliente" as cli
participant "Venta: objVenta" as venta
participant "List<TipoDescuento>: CatalogoDescuentos" as listaDesc
participant "TipoDescuento: descObj" as descObj
participant "List<Medicamento>: CatalogoMedicamentos" as listaMed
participant "Medicamento: objMed" as med
participant "DetalleVenta: det" as det

emp -> NegCtrl : iniciarNuevaVenta(dniCliente: String)
activate NegCtrl

    NegCtrl -> listaCli : buscarCliente(dniCliente: String)
    activate listaCli
    loop para cada c en lista
        listaCli -> cli : getDNI()
        activate cli
        cli --> listaCli : << dniActual: String >>
        deactivate cli
        
        alt dniCliente == dniActual
            listaCli --> NegCtrl : << objClienteEncontrado: Cliente >>
        end
    end
    deactivate listaCli

    NegCtrl -> venta ** : create(nroVta: Int, dniCliente: String, usuarioActual: String)
    activate venta
    venta --> NegCtrl : << objVenta: Venta >>
    deactivate venta
    
    NegCtrl -> venta : setFechaVenta(fecha: DateTime)
    NegCtrl -> venta : setTipoVta(tipo: String)
    NegCtrl -> venta : setEstadoVenta(estado: String)
    activate venta
    deactivate venta

    alt objClienteEncontrado != null
        NegCtrl -> cli : getMontoAcumulado()
        activate cli
        cli --> NegCtrl : << MontoAcumulado: Float >>
        deactivate cli

        alt MontoAcumulado > -80000.0
            NegCtrl -> venta : setClienteDNI(dniCliente: String) 
            ' (O setCliente objeto si decidimos agregarlo a la clase Venta)
            
            NegCtrl -> cli : esFrecuente(dniCliente: String)
            activate cli
            cli --> NegCtrl : << esFrecuente: Boolean >>
            deactivate cli

            alt esFrecuente == true
                note right of NegCtrl
                    Se aplicará SOLO si paga en Efectivo (Regla de Negocio).
                end note
                
                NegCtrl -> listaDesc : buscarDescuento(motivo: String)
                activate listaDesc
                loop búsqueda...
                    listaDesc -> descObj : getMotivo()
                    activate descObj
                    descObj --> listaDesc : << motivo: String >>
                    deactivate descObj
                    
                    alt motivo == "Cliente Frecuente"
                        listaDesc --> NegCtrl : << descObj: TipoDescuento >>
                    end
                end
                deactivate listaDesc

                alt descObj != null
                    NegCtrl -> descObj : getPorcentaje()
                    activate descObj
                    descObj --> NegCtrl : << porcentaje: Float >>
                    deactivate descObj
                    
                    ' Guardamos el porcentaje potencial en la venta
                    NegCtrl -> venta : aplicarDescuentoVenta(porcentaje: Float) 
                    activate venta
                    deactivate venta
                end
            end
        else Deuda Excesiva
             NegCtrl --> emp : <<Error: Deuda > $80.000>>
             NegCtrl -> venta : cancelarVta()
             NegCtrl -> venta : setEstadoVenta("Cancelado")
        end
    else Cliente Anónimo
        note right of NegCtrl: Se vende como cliente Anónimo <br> (Ya precargado en el sistema)
    end

    NegCtrl --> emp : <<Venta Iniciada>>
deactivate NegCtrl

loop Mientras carga productos
    
    alt AGREGAR PRODUCTO
        emp -> NegCtrl : agregarProducto(codBarra: String, cantidad: Int)
        activate NegCtrl
        
        NegCtrl -> listaMed : obtenerDisponibles(filtros: String)
        activate listaMed
        loop búsqueda
             listaMed -> med : getCodigoBarra()
             activate med
             med --> listaMed : << codigo: String >>
             deactivate med
             alt codigo == codBarra
                listaMed --> NegCtrl : << objMedEncontrado: Medicamento >>
             end
        end
        deactivate listaMed

        alt objMedEncontrado != null
             
             NegCtrl -> med : getRequiereReceta()
             activate med
             med --> NegCtrl : << requiereReceta: Boolean >>
             deactivate med

             alt requiereReceta == true
                NegCtrl --> emp : <<Error: Requiere Receta (Venta es Sin Receta)>>
             else
                NegCtrl -> med : getStock()
                activate med
                med --> NegCtrl : << stock: Int >>
                deactivate med
                
                alt stock >= cantidad
                    NegCtrl -> venta : agregarDetalle(codBarra: String, cantidad: Int)
                    activate venta
                        venta -> det ** : create(objMedEncontrado: Medicamento, cantidad: Int)
                        activate det
                        det --> venta : << nuevoDetalle: DetalleVenta >>
                        deactivate det
                        
                        det -> med : getPrecioUnitario()
                        activate med
                        med --> det : << precio: Float >>
                        deactivate med
                        
                    venta --> NegCtrl : <<NULL>>
                    deactivate venta
                    
                    NegCtrl --> emp : <<Producto Agregado>>
                else
                    NegCtrl --> emp : <<Error: Stock Insuficiente>>
                end
             end
        else
             NegCtrl --> emp : <<Error: Producto no encontrado>>
        end
        deactivate NegCtrl

    else FINALIZAR CARGA
        emp -> NegCtrl : confirmarVenta()
    end
end
@enduml