@startuml
title Venta Sin Receta

hide footbox

actor "Empleado" as emp
participant "Interfaz: NegCtrl" as NegCtrl
participant "List<Cliente>: CatalogoClientes" as listaCli
participant "Cliente: objCliente" as cli
participant "Venta: objVenta" as venta
participant "List<TipoDescuento>: CatalogoDescuentos" as listaDesc
participant "TipoDescuento: descObj" as descObj
participant "List<Medicamento>: objListaMed" as listaMed
participant "Medicamento: objMed" as med
participant "DetalleVenta: det" as det


emp -> NegCtrl : iniciarNuevaVenta(dniCliente: String)
activate NegCtrl

    NegCtrl -> listaCli : buscarCliente(dniCliente)
    activate listaCli
    
    loop para cada c en objListaClientes
        listaCli -> cli : getDNI()
        activate cli
        cli --> listaCli : << dniActual : String >>
        deactivate cli
        
        alt dniCliente == dniActual
            listaCli --> NegCtrl : << objClienteEncontrado : Cliente >>
        end
    end
    deactivate listaCli

    NegCtrl -> venta ** : create(nroVta, fechaVta : DateTime, tipoVta : string, total : decimal, dniCliente : int, nombreUsuario : string, estadoVenta : string)
    activate venta
    
    NegCtrl -> venta : setNroVta(nro)
    NegCtrl -> venta : setFechaVta(DateTime.Now())
    NegCtrl -> venta : setTipoVta("SinReceta")
    NegCtrl -> venta : setClienteDNI(dniCliente)
    
    venta --> NegCtrl : << objVenta : Venta >>
    deactivate venta

    alt objClienteEncontrado != null
        
        NegCtrl -> cli : getMontoAcumulado()
        activate cli
        cli --> NegCtrl : << MontoAcumulado : Float >>
        deactivate cli

        alt MontoAcumulado > -80000
            NegCtrl -> venta : setCliente(objClienteEncontrado)
            activate venta
            venta --> NegCtrl : <<NULL>>
            deactivate venta

            NegCtrl -> cli : esFrecuente(dniCliente)
            activate cli
            cli --> NegCtrl : << esFrecuente : Boolean >>
            deactivate cli

            alt esFrecuente == true
                NegCtrl -> listaDesc : buscarDescuento("Cliente Frecuente")
                activate listaDesc
                
                loop para cada d en CatalogoDescuentos
                    listaDesc -> descObj : getMotivo()
                    activate descObj
                    descObj --> listaDesc : << motivo : String >>
                    deactivate descObj
                    
                    alt motivo == 'Cliente Frecuente' y activo == true
                         listaDesc --> NegCtrl : << descObj : TipoDescuento >>
                    end
                end
                deactivate listaDesc

                ' Aplicación del Descuento
                alt descObj != null
                    NegCtrl -> descObj : getPorcentaje()
                    activate descObj
                    descObj --> NegCtrl : << porcentaje : Float >>
                    deactivate descObj
    
                    NegCtrl -> venta : aplicarDescuentoVenta(porcentaje)
                    activate venta
                    venta --> NegCtrl : <<NULL>>
                    deactivate venta
                end
            end
        else Deuda Excesiva
             emp -> NegCtrl : cancelarVenta()
             note right of NegCtrl: Bloqueo por regla de negocio:\nDeuda > $80.000
             NegCtrl -> venta : setEstado("Cancelado")
             activate venta
             venta --> NegCtrl : <<NULL>>
             deactivate venta
        end

    else cliente no encontrado (Anónimo)
        note right of NegCtrl
            Se continúa como venta
            a cliente anónimo
        end note
    end

    NegCtrl --> emp : <<NULL>>
deactivate NegCtrl

emp -> NegCtrl : filtrarMedicamentos(filtros)
activate NegCtrl
    NegCtrl -> listaMed : obtenerDisponibles(filtros)
    activate listaMed
    
    loop para cada med en Medicamento
        listaMed -> med : getMedicamento(filtros)
        activate med
        med --> listaMed : << coincide : booleano >>
        deactivate med

        alt coincide == true
            med --> listaMed : <<object : Medicamento>>
        end
    end
    
    listaMed --> NegCtrl : << List<Medicamento> >>
    deactivate listaMed

NegCtrl --> emp : List<Medicamento>
deactivate NegCtrl

loop Mientras la venta no esté confirmada
    
    alt AGREGAR PRODUCTO
        emp -> NegCtrl : agregarProducto(codBarra, cantidad)
        activate NegCtrl
        
        NegCtrl -> listaMed : buscarMedicamento(codBarra)
        activate listaMed
        listaMed --> NegCtrl : << objMedEncontrado : Medicamento >>
        deactivate listaMed

        alt objMedEncontrado != null AND stock >= cantidad
             
             NegCtrl -> med : esVentaBajoReceta()
             activate med
             med --> NegCtrl : << requiereReceta : Boolean >>
             deactivate med

             alt requiereReceta == true
                NegCtrl --> emp : <<NULL>>
             else
                NegCtrl -> venta : agregarDetalle(codBarra, cantidad)
                activate venta
                
                    venta -> det ** : create(objMedEncontrado, cantidad)
                    activate det
                    det --> venta : << nuevoDetalle >>
                    deactivate det

                    det -> med : getPrecioVenta()
                    activate med
                    med --> det : << precio : Float >>
                    deactivate med

                    note right of venta
                        SubTotal = Precio * cantidad
                    end note

                venta --> NegCtrl : <<NULL>>
                deactivate venta
                NegCtrl --> emp : <<List<Medicamento> : Medicamento>>
             end
        else Error Stock o No encontrado
             NegCtrl --> emp : <<NULL>>
        end
        deactivate NegCtrl

    else MODIFICAR CANTIDAD
        emp -> NegCtrl : modificarCantidad(codBarra, nuevaCantidad)
        activate NegCtrl
        
        NegCtrl -> venta : modificarCantidadDetalle(codBarra, nuevaCantidad)
        activate venta
            venta -> det : actualizarCantidad(nuevaCantidad)
            activate det
            deactivate det
            det --> venta : <<NULL>>
            deactivate det
            deactivate venta
            
        venta --> NegCtrl : <<NULL>>
        deactivate venta
        NegCtrl --> emp : <<List<Medicamento> : Medicamento>>
        deactivate NegCtrl

    else ELIMINAR PRODUCTO
        emp -> NegCtrl : eliminarProducto(codBarra)
        activate NegCtrl
        
        NegCtrl -> venta : eliminarDetallePorCodigo(codBarra)
        activate venta
            venta -> det : borrarlínea(codProd)
            venta --> NegCtrl : <<NULL>>
        deactivate venta
        NegCtrl --> emp : <<List<Medicamento> : Medicamento>>
        deactivate NegCtrl
        
    else FINALIZAR CARGA
        emp -> NegCtrl : confirmarVenta()
        note right of emp: Sale del loop para pagar
    end
end

activate venta
NegCtrl -> venta : calcularTotal()
venta --> NegCtrl : << total : Float >>
deactivate venta

NegCtrl -> venta : setTotal(total)
activate venta
venta --> NegCtrl : <<NULL>>
deactivate venta

NegCtrl --> emp : <<NULL>>
deactivate NegCtrl
@enduml