@startuml
title Venta Con Receta

hide footbox

actor "Empleado" as emp
participant "Interfaz: NegocioControlador" as NegCtrl
participant "Cliente: objCliente" as cli
participant "Venta: objVenta" as venta
participant "Receta: objReceta" as receta
participant "Cobertura: objCobertura" as cob
participant "Interfaz: ServicioObrasSociales" as srvOS

activate NegCtrl

    emp -> NegCtrl : ingresarDatosReceta(nroReceta: String, medico: String, fecha: Date)
    
    NegCtrl -> receta ** : create(nroReceta : int, fechaPrescripcion : DateTime, fechaValidez : DateTime, tipoReceta : string, obraSocialNombre: string)
    activate receta
    receta --> NegCtrl : << objReceta >>
    deactivate receta
    
    NegCtrl -> venta : setTipoVta("ConReceta")
    NegCtrl -> venta : setFechaVta(DateTime.Now())
    NegCtrl -> receta : setDetalles(nroReceta, medico, fecha)
    activate receta
    receta --> NegCtrl : <<NULL>>
    deactivate receta

    NegCtrl -> srvOS : verificarRecetaElectronica(nroReceta)
    activate srvOS
    srvOS --> NegCtrl : << esValida : Boolean >>
    deactivate srvOS

    emp -> NegCtrl : cargarDatosObraSocial(nombreOS: String, nroAfiliado: String)
    
    NegCtrl -> cob ** : create(numAfiliado : int, descuentoPorcentaje : int)
    activate cob
    cob --> NegCtrl : << objCobertura >>
    deactivate cob

    NegCtrl -> cob : setDatos(nroAfiliado)
    activate cob
    cob --> NegCtrl : <<NULL>>
    deactivate cob

    NegCtrl -> srvOS : validarAfiliacion(nombreOS, nroAfiliado)
    activate srvOS
    srvOS --> NegCtrl : << porcentaje : Float >>
    deactivate srvOS

    NegCtrl -> cob : setDescuentoPorcentaje(porcentaje)
    activate cob
    cob --> NegCtrl : <<NULL>>
    deactivate cob

    alt esValida == true AND porcentaje > 0
        NegCtrl -> venta : setReceta(objReceta)
        activate venta
        venta --> NegCtrl : <<NULL>>
        deactivate venta

        NegCtrl -> venta : setCobertura(objCobertura)
        activate venta
        venta --> NegCtrl : <<NULL>>
        deactivate venta
        
        NegCtrl -> venta : getNroVta()
        activate venta
        venta --> NegCtrl : << nroVta : Int >>
        deactivate venta

        NegCtrl -> srvOS : registrarRecetaEnVenta(nroReceta, nroVta)
        activate srvOS
        srvOS --> NegCtrl : <<NULL>>
        deactivate srvOS

        NegCtrl --> emp : <<NULL>>
    else Datos Inválidos
        NegCtrl -> venta : setEstado("CANCELADA")
        NegCtrl --> emp : <<NULL>>
    end

    NegCtrl --> emp : <<NULL>>
deactivate NegCtrl
@enduml