@startuml
!pragma teoz true
hide footbox
title Venta Sin Receta

actor "emp:Empleado" as emp
participant "cv:ControladorVentas" as cv
participant "cc:<<Singleton>>\nCatalogoClientes" as cc
participant "listaC[i]:Cliente" as itemCli
participant "cli:Cliente" as cli
participant "vta:Venta" as vta
participant "cm:<<Singleton>>\nCatalogoMedicamentos" as cm
participant "listaM[j]:Medicamento" as itemMed
participant "med:Medicamento" as med
participant "det:DetalleVenta" as det
participant "«multiobjeto»\ndetalles:DetalleVenta" as lineas

' =================================================================
' 1. INICIO Y CREACIÓN DE VENTA
' =================================================================
emp -> cv : iniciarNuevaVenta(dniCliente : INT)
activate cv

cv -> cc : buscarCliente(dniCliente : INT)
activate cc
loop hasta dniGuardado == dniCliente
    cc -> itemCli : getCliente()
    activate itemCli
    itemCli --> cc : <<dniGuardado : INT>>
    deactivate itemCli
end
cc --> cv : <<NULL O cli : Object Type : Cliente>>
deactivate cc

alt cli == NULL
    cv --> emp : <<"El cliente no se encontró">>
else cli != NULL
    create vta
    cv -> vta : CrearVenta(nroVta, cli, usuario, fecha)
    activate vta
    vta --> cv : <<NULL>>
    deactivate vta
end
deactivate cv

' =================================================================
' 2. AGREGAR PRODUCTO
' =================================================================
emp -> cv : escanearProducto(codBarra : INT, cantidad : INT)
activate cv

cv -> cm : buscarMedicamento(codBarra : INT)
activate cm
loop hasta cod == codBarra
    cm -> itemMed : getCodigoBarra()
    activate itemMed
    itemMed --> cm : <<cod : INT>>
    deactivate itemMed
end
cm --> cv : << NULL O med : Object Type : Medicamento>>
deactivate cm

alt med == NULL
    cv --> emp : <<"Medicamento no encontrado">>
else med != NULL
    cv -> vta : agregarDetalle(med : Object Type : Medicamento, cantidad : INT)
    activate vta
    
    Create det
    vta -> det : CrearDetalleVenta(med : Object Type : Medicamento, cantidad : INT)
    activate det
    det --> vta : <<det : Object Type : DetalleVenta>>
    deactivate det

    vta -> lineas : agregar(det : Object Type : DetalleVenta)
    activate lineas
    lineas --> vta : <<NULL>>
    deactivate lineas
    
    vta --> cv : <<NULL>>
    deactivate vta
    
    cv --> emp : "Producto agregado"
end
deactivate cv

' =================================================================
' 3. MODIFICAR CANTIDAD
' =================================================================
emp -> cv : modificarCantidad(codBarra : INT, nuevaCantidad : INT)
activate cv
    cv -> vta : modificarCantidadDetalle(codBarra : INT, nuevaCantidad : INT)
    activate vta

    loop para cada d en detalles
        vta -> lineas : getCodigoBarra()
        activate lineas
        lineas --> vta : <<codDetalle : INT>>
        deactivate lineas
        
        alt codDetalle == codBarra
            vta -> lineas : setCantidad(nuevaCantidad : INT)
            activate lineas
            lineas --> vta : <<NULL>>
            deactivate lineas
        end
    end
    vta --> cv : <<NULL>>
    deactivate vta
    cv --> emp : "Cantidad Modificada"
deactivate cv

' =================================================================
' 4. ELIMINAR PRODUCTO
' =================================================================
emp -> cv : quitarProducto(codBarra : INT)
activate cv

    cv -> vta : eliminarDetallePorCodigo(codBarra : INT)
    activate vta

    loop para cada d en detalles
        vta -> lineas : getCodigoBarra()
        activate lineas
        lineas --> vta : <<codDetalle : INT>>
        deactivate lineas
        
        alt codDetalle == codBarra
             vta -> lineas : eliminar(d : Object Type : DetalleVenta)
             activate lineas
             lineas --> vta : <<NULL>>
             deactivate lineas
        end
    end
    vta --> cv : <<NULL>>
    deactivate vta

    cv --> emp : "Producto Eliminado"
deactivate cv
@enduml