@startuml
!pragma teoz true
hide footbox
title Venta Con Receta

actor "emp:Empleado" as emp
participant "cv:ControladorVentas" as cv
participant "vta:Venta" as vta
participant "sos:ServicioObrasSociales" as sos

note over emp, sos
    Precondición: Se ha iniciado una venta y se ha seleccionado 
    la opción de "Venta con Receta".
end note

emp -> cv : validarReglasNegocio(dniCliente : INT)
activate cv

' 1. Validar Afiliación
cv -> sos : validarAfiliacion(obraSocialNombre : String, numAfiliado : INT)
activate sos
sos --> cv : <<esValido : BOOL>>
deactivate sos

alt esValido == TRUE
    ' 2. Verificar Receta
    cv -> sos : verificarRecetaElectronica(nroReceta : INT)
    activate sos
    sos --> cv : <<recetaOK : BOOL>>
    deactivate sos
    
    alt recetaOK == TRUE
        ' 3. Autorizar Cobertura
        cv -> sos : autorizarCobertura(nroVta : INT, obraSocialNombre : String, nroReceta : INT)
        activate sos
        sos --> cv : <<codAuth : INT>>
        deactivate sos
        
        ' 4. Actualizar el TIPO de venta en el objeto Venta
        cv -> vta : setTipoVta(conReceta)
        activate vta
        vta --> cv : <<NULL>>
        deactivate vta
        
        cv --> emp : "Receta Válida. Cobertura Autorizada."
    else recetaOK == FALSE
        cv --> emp : "Error: Receta inválida o vencida"
    end
else esValido == FALSE
    cv --> emp : "Error: Afiliación inválida"
end

deactivate cv
@enduml