@startuml
title Registro de Cliente (Alta)

hide footbox

actor "Empleado:Empleado" as emp
participant "gc:gestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoClientes" as cat
participant "clienteActual:Cliente" as cliente_actual

emp -> ctrl : nuevoCliente(dni, nombre, email, numTel)
activate ctrl

ctrl -> cat : buscarCliente(dni)
activate cat

loop [para cada c en clientes]
    cat -> cliente_actual : getDni()
    activate cliente_actual
    cliente_actual --> cat : << dniActual : String >>
    deactivate cliente_actual
    
    alt dni == dniActual
        cat --> ctrl : << c : Cliente >>
        deactivate cat
        
        ctrl --> emp : << "Error: Cliente ya registrado" >>

    else dni != dniActual

        deactivate cat

        create participant "nuevoCliente:Cliente" as nuevo_cliente
        ctrl -> nuevo_cliente : registrarCliente(dni, nombre, email, numTel)
        activate nuevo_cliente
        nuevo_cliente --> ctrl : << nuevoCliente : Cliente >>
        deactivate nuevo_cliente

        ctrl -> cat : agregarCliente(nuevoCliente)
        activate cat
        
        cat --> ctrl : << null >>
        deactivate cat
        
        ctrl --> emp : << "Cliente registrado correctamente" >>
        
    end
end

deactivate ctrl
@enduml