@startuml
title Registro de cliente

hide footbox

actor "Empleado:Empleado" as emp
participant "gc:GestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoClientes" as cat
participant "listaClientes[I]:Cliente" as cliente_actual
collections "«multiobjeto»\nlistaClientes: List<Cliente>" as lista_cli

emp -> ctrl : registrarCliente(dni: String, nombre: String, email: String, tel: String, dir: String, tipo: String)
activate ctrl

ctrl -> cat : buscarCliente(dni : String)
activate cat

loop hasta dni == dniActual
    cat -> cliente_actual : getDni()
    activate cliente_actual
    cliente_actual --> cat : << dniActual : String >>
    deactivate cliente_actual
    note over of cliente_actual: Si no se encuentra, retornar null
end

cat --> ctrl : << clienteEncontrado : Object Type : Cliente >>
deactivate cat

alt clienteEncontrado != null
    ctrl --> emp : << "Error: Cliente ya registrado" >>

else clienteEncontrado == null
    create participant "nuevoCli:Cliente" as nuevo_cli
    ctrl -> nuevo_cli : CrearCliente(dni: String, nombre: String, email: String, tel: String, dir: String, tipo: String)
    activate nuevo_cli
    nuevo_cli --> ctrl : << nuevoCli : Cliente >>
    deactivate nuevo_cli

    ctrl -> cat : registrarCliente(nuevoCli : Object Type : Cliente)
    activate cat
    cat -> lista_cli : add(nuevoCli : Object Type : Cliente)
    activate lista_cli
    lista_cli --> cat : << null >>
    deactivate lista_cli
    cat --> ctrl : << null >>
    deactivate cat
    
    ctrl --> emp : << "Cliente registrado correctamente" >>
    
end

deactivate ctrl
@enduml