@startuml
title Registro de cliente

hide footbox

actor "Empleado:Empleado" as emp
participant "gc:GestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoClientes" as cat
participant "clienteActual:Cliente" as cliente_actual

emp -> ctrl : registrarCliente(dni: String, nombre: String, email: String, tel: String, dir: String, tipo: String)
activate ctrl

ctrl -> cat : buscarCliente(dni)
activate cat

loop [para cada c en clientes]
    cat -> cliente_actual : getDni()
    activate cliente_actual
    cliente_actual --> cat : << dniActual : String >>
    deactivate cliente_actual
    
    alt dni == dniActual
        cat --> ctrl : << c : Cliente >>
        deactivate cat
        
        ctrl --> emp : << "Error: Cliente ya registrado" >>

    else dni != dniActual

        deactivate cat

        create participant "nuevoCli:Cliente" as nuevo_cli
        ctrl -> nuevo_cli : CrearCliente(dni: String, nombre: String, email: String, tel: String, dir: String, tipo: String)
        activate nuevo_cli
        nuevo_cli --> ctrl : << nuevoCli : Cliente >>
        deactivate nuevo_cli

        ctrl -> cat : registrarCliente(nuevoCli)
        activate cat
        
        cat --> ctrl : << null >>
        deactivate cat
        
        ctrl --> emp : << "Cliente registrado correctamente" >>
        
    end
end

deactivate ctrl
@enduml