@startuml
title Control e Informe

hide footbox

actor "Administrador" as admin
participant "gc:GestionControlador" as ctrl
participant "catV:<<Singleton>>\nCatalogoVentas" as cat_ventas
participant "v:Venta" as venta 
participant "catM:<<Singleton>>\nCatalogoMedicamentos" as cat_med
participant "m:Medicamento" as med
participant "gen:GeneradorReportes" as gen
participant "sc:ServicioCorreos" as srv_mail

admin -> ctrl : solicitarInforme(tipoInforme: String, filtro: String)
activate ctrl

alt tipo == "VENTAS"
    ctrl -> cat_ventas : obtenerVentasPorFecha(fecha: String)
    activate cat_ventas
    
    loop Para cada venta en la lista
        cat_ventas -> venta : getFecha()
        activate venta
        venta --> cat_ventas : << fechaRegistrada: Date >>
        deactivate venta
    end
    
    alt Sin Resultados
        cat_ventas --> ctrl : << null >>
        ctrl --> admin : << "Sin resultados" >>
    else Lista Encontrada
        cat_ventas --> ctrl : << listaVentas: List<Venta> >>
        ctrl --> admin : << listaVentas: List<Venta> >>
    end
    deactivate cat_ventas

else tipo == "STOCK"
    ctrl -> cat_med : buscarMedicamentos(filtro: String)
    activate cat_med
    
    loop Para cada medicamento en la lista
        cat_med -> med : getNombre()
        activate med
        med --> cat_med : << nombre: String >>
        deactivate med
    end
    
    alt Sin Resultados
        cat_med --> ctrl : << null >>
        ctrl --> admin : << "Sin resultados" >>
    else Lista Encontrada
        cat_med --> ctrl : << listaMed: List<Medicamento> >>
        ctrl --> admin : << listaMed: List<Medicamento> >>
    end
    deactivate cat_med
end

opt El administrador decide exportar
    admin -> ctrl : procesarInforme(listaDatos: List, accion: String)

    ctrl -> gen : generarPDF(listaDatos: List)
    activate gen
    gen --> ctrl : << archivoGenerado: File >>
    deactivate gen

    alt accion == "GUARDAR"
        ctrl --> admin : << Descarga (archivoGenerado) >>
        
    else accion == "ENVIAR_PROVEEDOR"
        ctrl -> srv_mail : enviarCorreo(archivoPdf: File, emailProv: String)
        activate srv_mail
        
        alt Error envio
            srv_mail --> ctrl : << false >>
            ctrl --> admin : << "Error: Falló el envío" >>
        else Envio Exitoso
            srv_mail --> ctrl : << true >>
            ctrl --> admin : << "Éxito: Informe enviado" >>
        end
        deactivate srv_mail
    end
end

deactivate ctrl
@enduml