@startuml
title Eliminación de Medicamento (Lógica Correcta)

hide footbox

actor "Administrador: Admin" as admin
participant "NegocioControlador: Interfaz" as NegCtrl
participant "List<Medicamento>: medicamentos" as listaMeds
participant "Medicamento: objMed" as med
participant "List<Venta>: ventas" as listaVentas
participant "Venta: v" as venta

admin -> NegCtrl : eliminarMedicamento(codigoBarra: String)
activate NegCtrl

    NegCtrl -> listaMeds : buscarMedicamento(codigoBarra)
    activate listaMeds
    
    loop [para cada m en medicamentos]
        listaMeds -> med : getCodigoBarra()
        activate med
        med --> listaMeds : << codigoActual >>
        deactivate med
        
        alt codigoBarra == codigoActual
            listaMeds --> NegCtrl : << objMed : Medicamento >>
            break
        end
    end
    
    listaMeds --> NegCtrl : << NULL >>
    deactivate listaMeds

    alt objMed == NULL
        NegCtrl --> admin : << Error: El medicamento no existe >>
        
    else medicamento encontrado (EL ELSE QUE FALTABA)
        

        NegCtrl -> listaVentas : verificarUsoEnVentas(objMed)
        activate listaVentas
        
        loop [para cada v en ventas]
            listaVentas -> venta : contieneMedicamento(objMed)
            activate venta
            venta --> listaVentas : << tieneElMedicamento : Boolean >>
            deactivate venta
            
            alt (tieneElMedicamento == true) AND (venta.estado == PENDIENTE)
                listaVentas --> NegCtrl : << CONFLICTO >>
                break
            end
        end
        
        listaVentas --> NegCtrl : << OK >>
        deactivate listaVentas
        
        alt Se recibió CONFLICTO
            NegCtrl --> admin : << Error: Asociado a venta pendiente >>
            
        else Se recibió OK (Eliminación Exitosa)
            NegCtrl -> listaMeds : quitarMedicamento(objMed)
            activate listaMeds
            listaMeds --> NegCtrl : << TRUE >>
            deactivate listaMeds
            
            NegCtrl --> admin : << Éxito: Eliminado >>
        end
        
    end ' Fin del ELSE gigante

deactivate NegCtrl
@enduml