@startuml
!pragma teoz true
hide footbox
title Eliminación de Medicamentos

actor "Administrador:Admin" as admin
participant "gc:FarmaciaControlador" as gc
participant "catMed:<<Singleton>>\nCatalogoMedicamentos" as catMed
participant "listaMed[i]:Medicamento" as arrayMed
collections "<<multiobjeto>>\nlistaMed:List" as lista_med
participant "catVentas:<<Singleton>>\nCatalogoVentas" as catVentas
participant "listaVentas[j]:Venta" as arrayVentas
participant "detalles[k]:DetalleVenta" as arrayDetalles

admin -> gc : eliminarMedicamento(codBarra : int)
activate gc

gc -> catMed : buscarMedicamento(codBarra : int)
activate catMed

loop para cada Medicamento en listaMed
    catMed -> arrayMed : getCodigoBarra()
    activate arrayMed
    arrayMed --> catMed : <<codActual : int>>
    
    deactivate arrayMed
end

catMed --> gc : <<medEncontrado : Medicamento>>
deactivate catMed


alt No se encontró el Medicamento
    
    gc --> admin : "Error: El medicamento no existe"
    
else Se encontró el Medicamento

    gc -> catVentas : tieneVtasAsociadas(medEncontrado)
    activate catVentas
    
    loop para cada v en listaVentas
        
        catVentas -> arrayVentas : getDetallesDeVenta()
        activate arrayVentas
        arrayVentas --> catVentas : <<listaDetalles : List<DetalleVenta>>>
        deactivate arrayVentas
        
        loop para cada d en listaDetalles
            catVentas -> arrayDetalles : getCodigoBarra()
            activate arrayDetalles
            arrayDetalles --> catVentas : <<codDetalle : int>>
            deactivate arrayDetalles
            
            alt codDetalle == codBarra
                note right of catVentas
                    vtaAsociada = TRUE
                end note
            else codDetalle != codBarra
                note right of catVentas
                    vtaAsociada = FALSE
                end note
            end
        end
    end
    catVentas --> gc : << vtaAsociada : Bool >>
    deactivate catVentas

    alt vtaAsociada == TRUE
        
        gc --> admin : "Error: No se puede eliminar porque el medicamento tiene ventas asociadas"
        
    else vtaAsociada == FALSE
        
        gc -> catMed : eliminarMedicamento(medEncontrado : Medicamento)
        activate catMed
        
        catMed -> lista_med : remove(medEncontrado : Medicamento)
        activate lista_med
        lista_med --> catMed : <<null>>
        deactivate lista_med
        
        catMed --> gc : <<null>>
        deactivate catMed
        
        gc --> admin : "Medicamento eliminado exitosamente"
        deactivate gc
        
    end

end

@enduml