@startuml
title Carga de Tipo de Descuento
hide footbox

actor "Administrador:Admin" as admin
participant "gc:GestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoDescuentos" as cat
participant "listaDesc[i]:TipoDescuento" as listDesc
collections "<<multiobjeto>>\nlistaDesc:List" as lista_desc

admin -> ctrl : registrarTipoDescuento(motivo: String, porcentaje: Float, fechaInicio: Date, fechaFin: Date)
activate ctrl

ctrl -> cat : buscarDescuento(motivo : String)
activate cat

loop hasta motivo == motivoActual
    cat -> listDesc : getMotivo()
    activate listDesc
    listDesc --> cat : <<motivoActual : String>>
    
    note right of listDesc : Si no se encuentra, retornar null
    
    deactivate listDesc
end

cat --> ctrl : <<descuentoEncontrado : Object Type : TipoDescuento>>
deactivate cat

alt descuentoEncontrado != null
    
    ctrl --> admin : "Error: Tipo de descuento ya registrado"

else descuentoEncontrado == null
    
    create participant "nuevoTD:TipoDescuento" as td
    ctrl -> td : CrearTipoDescuento(motivo: String, porcentaje: Float, fechaInicio: Date, fechaFin: Date)
    activate td
    td --> ctrl : <<nuevoTD : TipoDescuento>>
    deactivate td
    
    ctrl -> cat : agregarDescuento(nuevoTD : Object Type : TipoDescuento)
    activate cat
    
    cat -> lista_desc : add(nuevoTD : Object Type : TipoDescuento)
    activate lista_desc
    lista_desc --> cat : <<null>>
    deactivate lista_desc
    
    cat --> ctrl : <<null>>
    deactivate cat
    
    ctrl --> admin : "Éxito: Descuento guardado"

end

deactivate ctrl
@enduml