@startchen DER
left to right direction
' ---------- ENTIDADES (solo nombre) ----------

entity Empleado {
    __nombreEmpleado__
}

entity Usuario {
    tipoUsuario
    __nombreUsuario__
    contraseña
}

entity Cliente {
    nombreCliente
    email
    númTel
    __DNI__
    SaldoCtaCorriente
    tipoCliente
    montoAcumulado
}

entity ObraSocial {
    __NombreObraSocial__
}

entity Venta {
    __nroVta__
    tipoVta
    fechaVta
    montoTotal
    tipoPago
    cuotas
    estadoVenta
}

entity DetalleVenta {
    __nroDetalleVenta__
    precio
    montoFinal
}

entity Pago {
    __numTransaccion__
    tipoPago
    monto
    cuotas
    fechaPago
    estadoPago
}

entity Drogueria{
    __nombre__
    direccion
    email
    númTel
    formatoEnvío
}

entity Medicamento {
    __codBarra__
    nombreMed
    descripción
    drogueria
    precioMedUnitario
    stock
}

entity Asistencia {
    __fecha__
    horaEntrada
    horaSalida
    estado
}

entity Ticket {
    __nroTicket__
    DatosFarmacia
    fechaHora
    DatosCliente
    EstadoTicket
    pdfPath
}

entity Medico {
    __matriculaMed__
    nombreMedico
}

entity Cobertura {
    __numAfiliado__
    Descuento
}

entity Receta {
    __nroReceta__
}

entity DetalleReceta{
    fechaPrescripción
    matriculaMedico
    __productosRecetados__
}

entity DetallePedido {
    __numPedido__
    nombreMed
    drogueria
    estadoPedido
    pathPdf
}

entity TipoDescuento{
    __motivo__
    porcentaje
    fechainicio
    fechaFinal
    estado
}
' ---------- RELACIONES ----------

relationship Obtiene {
}
relationship Aplica {
}
relationship Genera {
}
relationship Afiliado {
}
relationship Prescribe{
}
relationship Contiene{
}
relationship Tiene {
}
relationship Gestiona {
}
relationship Incluye {
}
relationship Detalla {
}
relationship Lista {
}
relationship Asociado {
}
relationship Brinda {
}
relationship Corresponde {
}
relationship Asociada {
}
relationship Representa {
}
relationship Modifica {
}
relationship Vinculado {
}
relationship Engloba{
}
relationship Abarca{
}
relationship Crea{
}
relationship Es_enviado{
}
relationship Se_Concreta{
}
' ---------- CONEXIONES (multiplicidades Chen puro) ----------


TipoDescuento -N- Obtiene
Obtiene -N- Cliente

TipoDescuento -1- Aplica
Aplica -N- Venta

Empleado -1- Representa
Representa -1- Usuario

Usuario -1- Gestiona
Gestiona -N- Venta

Cliente -1- Asociado
Asociado -N- Venta

Usuario -1- Tiene
Tiene -N- Asistencia

Venta -1- Incluye
Incluye -N- DetalleVenta

Medicamento -1- Detalla
Detalla -N- DetalleVenta

Cobertura -1- Modifica
Modifica -N- Venta

Cliente -1- Afiliado
Afiliado -N- Cobertura

Medicamento -1- Lista
Lista -N- DetallePedido

Venta -1- Genera
Genera -1- Ticket

Medico -1- Prescribe
Prescribe -N- Receta

Receta -1- Abarca
Abarca -N- DetalleReceta

Medicamento -1- Engloba
Engloba -N- DetalleReceta

Receta -1- Asociada
Asociada -1- Venta

ObraSocial -1- Brinda
Brinda -N- Cobertura

Receta -N- Vinculado
Vinculado -1- Venta

Venta -1- Se_Concreta
Se_Concreta -N- Pago

Receta -N- Contiene
Contiene -N- Medicamento

Receta -N- Corresponde
Corresponde -1- Cliente

Usuario -1- Crea
Crea -N- DetallePedido

DetallePedido -N- Es_enviado
Es_enviado -1- Drogueria

@endchen
