@startchen DER

' ---------- ENTIDADES (solo nombre) ----------
entity Usuario {
    nombreUsuario : str
    contraseña : str
    montoTotalVendido : float
    tipoUsuario : int
}
entity Empleado {
    nombre : str
    apellido : str
    sueldo : float
    montoTotalVendido : float
    asistencia : char

}
entity Cliente {
    nombreCliente : str
    apellidoCliente : str
    email : str
    númTel : str
    DNI : str
    DetallesPedidos : 
    SaldoCtaCorriente : float
}
entity ObraSocial {
    numAfiliado : str
    nomObraSocial : str
    fechaPrescripción : date
    fechaVenta : date
    matriculaMed : int
    productosRecetados : str
}
entity Afiliacion {
}
entity Venta {    
    tipoVta : int
    DatosCliente : compuesto
    fechaVta : date
    montoTotal : float
    tipoPago : str
    cuotas : int
}
entity DetalleVenta {
    nombreMed : str
    precio : float
    montoFinal : float
}
entity Medicamento {
    codBarra : int
    nombreMed : str
    descripción : str
    laboratorio : str
    precioMedUnitario : float
    stock : int
}
entity Asistencia {
   fecha : date
    horaEntrada : datetime
    horaSalida : datetime
    estado : str
}
entity Ticket {
    DatosFarmacia : 
    fechaHora : datetime
    DatosCliente : 
    detallesPedido : 
}

' ---------- RELACIONES ----------
relationship Realiza {
}
relationship Compra {
}
relationship Incluye {
}
relationship Tiene {
}
relationship Genera {
}
relationship AfiliacionRel {
}
relationship Representa {
}



' ---------- CONEXIONES (multiplicidades Chen puro) ----------

Usuario -N- Realiza
Realiza -1- Venta

Cliente -N- Compra
Compra -1- Venta

Venta -N- Incluye
Incluye -1- DetalleVenta

DetalleVenta -1- Medicamento

Empleado -N- Tiene
Tiene -N- Asistencia

Usuario -N- Genera
Genera -1- Ticket

Cliente -1- Afiliacion
Afiliacion -1- ObraSocial

Afiliacion -1- AfiliacionRel
AfiliacionRel -1- ObraSocial

Usuario -1- Representa
Representa -1- Empleado

@endchen

