@startchen DER
left to right direction
' ---------- ENTIDADES (solo nombre) ----------

entity Empleado {
    __idEmpleado__
    nombreEmpleado
    sueldo
}


entity Usuario {
    __tipoUsuario__
    nombreUsuario
    contraseña
}

entity Cliente {
    __numAfiliado__
    nombreCliente
    email
    númTel
    DNI
    SaldoCtaCorriente
}
entity ObraSocial {
    __NombreObraSocial__
    productosRecetados
}
entity Venta {
    __nroVta__
    tipoVta
    DatosCliente
    fechaVta
    montoTotal
    tipoPago
    fechaVenta
    cuotas
entity DetalleVenta {
    __idDetalleVenta__
    nombreMed
    precio
    montoFinal
}
entity Medicamento {
    __codBarra__
    nombreMed
    descripción
    laboratorio
    precioMedUnitario
    stock
}
entity Asistencia {
    __fecha__
    horaEntrada
    horaSalida
    estado
}
entity Ticket {
    __nroTicket__
    DatosFarmacia
    fechaHora
    DatosCliente
}

entity Medico {
    __matriculaMed__
    nombreMedico
}

entity Descuento {
    porcentaje
}


entity Receta {
    __nroReceta__
    fechaPrescripción
    matriculaMedico
}

entity DetallePedido {
    __idDetallePedido__
    nombreMed
    precio
    montoFinal
}

' ---------- RELACIONES ----------

relationship Genera {
}
relationship Afiliado {
}
relationship Prescribe{
}
relationship Contiene{
}
relationship Caracteriza{
}
relationship Tiene {
}
relationship Gestiona {
}
relationship Incluye {
}
relationship Detalla {
}
relationship Lista {
}
relationship Asociado {
}
relationship Vinculado {
}
relationship Determina {
}
relationship Corresponde {
}
relationship Aplica {
}
relationship Representa {
}
relationship Cuenta {
}
relationship Modifica {
}
' ---------- CONEXIONES (multiplicidades Chen puro) ----------

Empleado -1- Representa
Representa -1- Usuario

Usuario -1- Gestiona
Gestiona -N- Venta

Cliente -1- Asociado
Asociado -N- Venta

Usuario -1- Tiene
Tiene -N- Asistencia

Venta -1- Incluye
Incluye -N- DetalleVenta

DetalleVenta -1- Detalla
Detalla -N- Medicamento

Descuento -1- Modifica
Modifica -N- Venta

DetallePedido -1- Lista
Lista -N- Medicamento

Venta -1- Genera
Genera -1- Ticket

DetalleVenta -1- Caracteriza
Caracteriza -1- Ticket

Medico -1- Prescribe
Prescribe -N- Receta

Medico -N- Vinculado
Vinculado -N- ObraSocial

ObraSocial -1- Determina
Determina -1- Descuento

Cliente -1- Cuenta
Cuenta -1- Descuento

Descuento -1- Aplica
Aplica -N- Receta

Receta -N- Contiene
Contiene -N- Medicamento

Cliente -1- Afiliado
Afiliado -1- ObraSocial

Receta -N- Corresponde
Corresponde -1- Cliente

@endchen