﻿@startchen DER
left to right direction
' ---------- ENTIDADES (solo nombre) ----------

entity Empleado {
    __idEmpleado__
    nombreEmpleado
    sueldo

}
entity Cliente {
    __idCliente__
    nombreCliente
    email
    númTel
    DNI
    SaldoCtaCorriente
}
entity ObraSocial {
    __numAfiliado__
    nomObraSocia
    fechaVenta
    matriculaMed
    productosRecetados
}
entity Venta {
    __nroVta__
    tipoVta
    DatosCliente
    fechaVta
    montoTotal
    tipoPago
    cuotas
entity DetalleVenta {
    __idDetalleVenta__
    nombreMed
    precio
    montoFinal
}
entity Medicamento {
    __codBarra__
    nombreMed
    descripción
    laboratorio
    precioMedUnitario
    stock
}
entity Asistencia {
    __idAsistencia__
    fecha
    horaEntrada
    horaSalida
    estado
}
entity Ticket {
    __nroTicket__
    DatosFarmacia
    fechaHora
    DatosCliente
}

entity Receta {
    __nroReceta__
    fechaPrescripción
    matriculaMedico

}

entity DetallePedido {
    __idDetallePedido__
    nombreMed
    precio
    montoFinal

}

' ---------- RELACIONES ----------

relationship Genera {
}
relationship Afiliado {
}
relationship Prescribe{
}
relationship Contiene{
}
relationship Caracteriza{
}
relationship Tiene {
}
relationship Gestiona {
}
relationship Incluye {
}
relationship Detalla {
}
relationship Lista {
}
relationship Asociado {
}
relationship Corresponde {
}
' ---------- CONEXIONES (multiplicidades Chen puro) ----------

Empleado -1- Gestiona
Gestiona -N- Venta

Cliente -1- Asociado
Asociado -N- Venta

Empleado -1- Tiene
Tiene -1- Asistencia

Venta -N- Incluye
Incluye -1- DetalleVenta

DetalleVenta -1- Detalla
Detalla -N- Medicamento

DetallePedido -1- Lista
Lista -N- Medicamento

Venta -1- Genera
Genera -1- Ticket

DetalleVenta -1- Caracteriza
Caracteriza -1- Ticket

Receta -1- Prescribe
Prescribe -1- ObraSocial

Receta -1- Contiene
Contiene -N- Medicamento

Cliente -1- Afiliado
Afiliado -1- ObraSocial

Receta -N- Corresponde
Corresponde -1- Cliente

@endchen