@startuml
title Carga de Proveedores (Alta) - Final

hide footbox

actor "Administrador:Admin" as admin
participant "gc:gestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoProveedores" as cat
participant "prov[i]:Proveedor" as prov_iter
participant "nuevoProv:Proveedor" as nuevo_prov

admin -> ctrl : nuevoProveedor(nombre, email, telefono, canalPreferido)
activate ctrl

ctrl -> cat : buscarProveedor(nombre)
activate cat

loop [para cada p en proveedores]
    cat -> prov_iter : getNombre()
    activate prov_iter
    prov_iter --> cat : << nombreActual : String >>
    deactivate prov_iter
    
    alt nombre == nombreActual
        cat --> ctrl : << p : Proveedor >>
        
        ctrl --> admin : << "Error: Proveedor ya registrado" >>

    else nombre != nombreActual
    
        ctrl -> nuevo_prov : crearProveedor(nombre, email, telefono, canalPreferido)
        activate nuevo_prov
        nuevo_prov --> ctrl : << nuevoProv : Proveedor >>
        deactivate nuevo_prov

        ctrl -> cat : agregarProveedor(nuevoProv)
        activate cat
        
        cat --> ctrl : << null >>
        deactivate cat
        
        ctrl --> admin : << "Éxito: Proveedor registrado" >>
        
    end
end

deactivate cat
deactivate ctrl
@enduml