@startuml
title Carga de proveedores
hide footbox

actor "Administrador:Admin" as admin
participant "gc:GestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoDroguerias" as cat
participant "listaProv[i]:Drogueria" as drog_actual
collections "«multiobjeto»\nlistaProveedores :List<Drogueria>" as lista_drog


admin -> ctrl : registrarDrogueria(nombre: String, email: String, tel: String, dir: String, cuit: String, canalPreferido: String)
activate ctrl

ctrl -> cat : buscarProveedor(nombre : String)
activate cat

loop hasta nombre == nombreActual
    cat -> drog_actual : getNombre()
    activate drog_actual
    drog_actual --> cat : << nombreActual : String >>
    deactivate drog_actual
    note over of drog_actual: Si no se encuentra, retornar null
end

        cat --> ctrl : << drogEncontrada : Object Type : Drogueria >>
        deactivate cat

    alt drogEncontrada != null
        ctrl --> admin : << "Error: Droguería ya registrada" >>

    else drogEncontrada == null

        deactivate cat
    
        create participant "nuevaDrog:Drogueria" as nuevo_drog
        ctrl -> nuevo_drog : CrearDrogueria(nombre: String, email: String, tel: String, dir: String, cuit: String, canalPreferido: String)
        activate nuevo_drog
        nuevo_drog --> ctrl : << nuevaDrog : Drogueria >>
        deactivate nuevo_drog

        ctrl -> cat : agregarProveedor(nuevaDrog : Object Type : Drogueria)
        activate cat
        cat -> lista_drog : add(nuevaDrog : Object Type : nuevaDrog)
        activate lista_drog
        lista_drog --> cat : << null >>
        deactivate lista_drog
        cat --> ctrl : << null >>
        deactivate cat
        
        ctrl --> admin : << "Éxito: Droguería registrada" >>
        
    end

deactivate ctrl
@enduml