@startuml
title Eliminación de Tipo de Descuento
hide footbox

actor "Administrador:Admin" as admin
participant "gc:FarmaciaControlador" as ctrl
participant "catDesc:<<Singleton>>\nCatalogoDescuentos" as cat
participant "listaDesc[i]:TipoDescuento" as listTD
participant "descEncontrado:TipoDescuento" as td

admin -> ctrl : eliminarDescuento(motivo: String)
activate ctrl

ctrl -> cat : buscarDescuento(motivo : String)
activate cat

loop hasta motivoLista == motivo
    cat -> listTD : getMotivo()
    activate listTD
    listTD --> cat : <<motivoLista : String>>
    
    deactivate listTD
end

cat --> ctrl : <<descEncontrado : TipoDescuento>>
deactivate cat

alt No se encontró el Tipo de Descuento
    
    ctrl --> admin : "Error: El tipo de descuento no existe"

else Se encontró el Tipo de Descuento

    ctrl -> cat : eliminarDescuento(descEncontrado : TipoDescuento)
    activate cat
    
    cat -> td : setActivo(false)
    activate td
    td --> cat : <<null>>
    deactivate td
    
    cat --> ctrl : <<null>>
    deactivate cat
    
    ctrl --> admin : "Éxito: Tipo de descuento dado de baja correctamente."
    deactivate ctrl

end

@enduml