@startuml CLASES
left to right direction
skinparam classAttributeIconSize 0

' ----------------- PERSONAS -----------------
class Persona {
    - nombre
    - email
    - numTel
    - direccion

    + setPersona(dni, nombre, email, numTel, direccion)
    + getPersona(dni)
    + actualizarContacto(dni, email, numTel, direccion)
}

class PersonaFisica {
    - DNI
}
class PersonaJuridica {
    - CUIT
}

Persona <|-- PersonaFisica
Persona <|-- PersonaJuridica

' ----------------- USUARIO / EMPLEADO -----------------
class Usuario {
    - nombreUsuario
    - contraseña

    + setUsuario(nombreUsuario, contraseña)
    + getUsuario(nombreUsuario)
}

class Empleado {
    - legajo
}

Empleado -- Usuario

enum TipoUsuario {
    Administrador
    Farmaceutico
}
Usuario -- TipoUsuario

' ----------------- ASISTENCIA -----------------
class Asistencia {
    - fecha
    - horaEntrada
    - horaSalida
    - estado

    + registrarAsistencia(nombreUsuario, fecha, horaEntrada, horaSalida, estado)
}
enum EstadoAsistencia {
    Licencia
    Ausente
    Presente
    Tarde
}
Asistencia -- EstadoAsistencia
Empleado -- Asistencia

' ----------------- CLIENTE -----------------
class Cliente {
    - DNI
    - nombre
    - SaldoCtaCorriente
    - tipoCliente
    - montoAcumulado
    - email
    - numTel

    + getCliente(dni)
    + setCliente(dni, nombre, email, numTel, tipoCliente)
    + acumularGasto(dni, monto)
    + registrarPagoCuentaCorriente(dni, monto)
    + esFrecuente(dni)
    + mostrarClientes()
}
PersonaFisica <|-- Cliente
PersonaFisica <|-- Medico
PersonaFisica <|-- Empleado

' ----------------- MEDICO / RECETA -----------------
class Medico {
    - matriculaMed
    - nombreMedico

    + getMedico(matricula)
}
class Receta {
    - nroReceta
    - fechaPrescripcion
    - fechaValidez
    - tipoReceta
    - obraSocialNombre

    + obtenerReceta(nroReceta)
    + validarReceta(nroReceta)
    + obtenerDetalleReceta(nroReceta)
}
class DetalleReceta {
    - fechaPrescripcion
    - productosRecetados
}
Medico -- Receta
Receta *-- DetalleReceta
Cliente -- Receta

' ----------------- OBRA SOCIAL / COBERTURA -----------------
class ObraSocial {
    - nombreObraSocial
    - contacto

    + getObraSocial(nombre)
}
class Cobertura {
    - numAfiliado
    - descuentoPorcentaje
}
Cliente -- Cobertura
Cobertura -- ObraSocial

' ----------------- MEDICAMENTO / DROGUERIA -----------------
class Medicamento {
    - codigoBarra
    - nombre
    - precioUnitario
    - requiereReceta
    - controlado
    - cadenaFrio
    - stock
    - stockMinimo
    - drogueriaNombre

    + consultarStock()
    + disminuirStock(cantidad)
    + aumentarStock(cantidad)
    + estaPorDebajoStockMinimo()
    + MostrarMedicamentos()
}
class Drogueria {
    - nombre
    - email
    - telefono
    - canalPreferido

    + actualizarContacto(nombre, email, telefono, canalPreferido)
}
PersonaJuridica <|-- Drogueria
Drogueria -- Medicamento

' ----------------- VENTAS / DETALLE / PAGO / TICKET -----------------
enum TipoVenta {
    conReceta
    sinReceta
}

enum EstadoVenta {
    Pendiente
    Pagado
    Cancelado
}

class Venta {
    - nroVta
    - fechaVenta
    - tipoVta
    - total
    - clienteDNI
    - nombreUsuario
    - estadoVenta

    + agregarDetalle(codigoBarra, cantidad)
    + eliminarDetallePorCodigo(codigoBarra)
    + modificarCantidadDetalle(codigoBarra, nuevaCantidad)
    + calcularTotal()
    + aplicarDescuento(tipoDescuentoId)
    + validarRecetas()
    + confirmarPago(numTransacción)
    + marcarEstado(estadoVenta)
    + cancelar()
    + finalizar(tipoPago, nroCuotas)
}
Venta ..> TipoVenta
Venta -- EstadoVenta

class DetalleVenta {
    - nroDetalle
    - codigoBarra
    - cantidad
    - precioUnitario
    - subtotal

    + calcularSubtotal(cantidad, precioUnitario)
    + actualizarCantidad(nuevaCantidad)
}
Venta *-- DetalleVenta
DetalleVenta -- Medicamento

class Pago {
    - numTransacción
    - tipoPago
    - monto
    - cuotas


    + crearPago(nroVta, tipoPago, monto, cuotas)
    + asignarNumTransaccion(numTransacción)
    + procesarRespuestaPasarela(estadoPago, numTransacción)
    + marcarEstadoPago(numTransacción, estado)
}
Venta -- Pago

enum estadoPago {
    aprobado
    rechazado
}
Pago -- estadoPago

class Ticket {
    - nroTicket
    - fechaHora
    - pdfPath

    + generarTicket(nroVta)
}

enum Estado{
    error
    creado
    enviado
}
Ticket -- Estado
Venta -- Ticket

' ----------------- TIPO DESCUENTO -----------------
class TipoDescuento {
    - motivo
    - porcentaje
    - fechaInicio
    - fechaFin
    - activo

    + esAplicable(nroVta)
}
TipoDescuento -- Venta
TipoDescuento -- Cliente

' ----------------- PEDIDOS / DETALLEPEDIDO -----------------

class Pedido {
    - numPedido
    - proveedorNombre
    - fechaPedido

    + calcularTotal()
    + agregarLinea(codigoBarra, cantidad)
}

enum EstadoPedido{
    error
    creado
    enviado
}

class DetallePedido {
    - codigoBarra
    - nombreMedicamento
    - cantidad
    - precioUnitario
    - subtotal

    + calcularSubtotal(codigoBarra, cantidad, precioUnitario)
}
Pedido *-- DetallePedido
Pedido -- Drogueria
Pedido -- EstadoPedido

' ----------------- CONTROLADORES / SERVICIOS -----------------
interface NegocioControlador {
    + iniciarSesion(nombreUsuario, contraseña)
    + cerrarSesion()
    + crearUsuario(nombreUsuario, contraseña, tipoUsuario)
    + modificarUsuario(nombreUsuario, campos)
    + buscarUsuarios(filtros)

    + crearCliente(dni, nombre, email, numTel, tipoCliente)
    + modificarCliente(dni, camposContacto)
    + buscarClientes(filtros)
    + abrirCuentaCorriente(dni)
    + registrarPagoCuentaCorriente(dni, monto)

    + crearMedicamento(codigoBarra, nombre, precioUnitario, stock, stockMinimo, drogueriaNombre)
    + modificarMedicamento(codigoBarra, campos)
    + eliminarMedicamento(codigoBarra)
    + buscarMedicamentos(filtros)
    + ajustarStock(codigoBarra, cantidad)

    + crearDrogueria(nombre, email, telefono, canalPreferido)
    + modificarDrogueria(nombre, campos)
    + eliminarDrogueria(nombre)
    + buscarDroguerias(filtros)

    + crearVenta(clienteDNI, tipoVta)
    + agregarLineaVenta(nroVta, codigoBarra, cantidad)
    + editarLineaVenta(nroVta, codigoBarra, nuevaCantidad)
    + eliminarLineaVenta(nroVta, codigoBarra)
    + cancelarVenta(nroVta)
    + aplicarDescuentoVenta(nroVta, motivo)
    + finalizarVenta(nroVta, tipoPago, nroCuotas)
    + buscarVentas(filtros)

    + procesarPago(nroVta, tipoPago)
    + procesarRespuestaPago(nroVta, estadoPago, numTransacción)
    + registrarTransaccion(nroVta, numTransacción, estadoPago)
    + actualizarEstadoVenta(nroVta, estadoVenta)
    + reintentarEnvioComprobante(nroVta)
}

interface ServicioPedidos {
    + generarPedidoAutomatico()
    + crearPedidoManual(proveedorNombre, listaItems)
    + generarDetallePedido(numPedido, codigoBarra, cantidad)
    + generarPDFPedido(numPedido)
    + seleccionarCanalEnvioProveedor(proveedorNombre)
    + enviarPedido(numPedido, proveedorNombre)
    + enviarViaWhatsApp(numPedido, telefono)
    + enviarViaEmail(numPedido, email)
    + registrarEnvioPedido(numPedido, proveedorNombre, canal, estado)
    + ObtenerEstadoPedido(numPedido)
    + ReintentarDetallePedido(numPedido)

    + generarPDFTicket(nroVta)
    + enviarComprobante(nroVta, clienteDNI)
    + enviarViaWhatsAppComprobante(nroVta, telefono)
    + enviarViaEmailComprobante(nroVta, email)
    + guardarTicketLocal(nroVta)
    + registrarEnvioComprobante(nroVta, canal, estado)
    + ObtenerEstadoTicket(nroTicket)
    + ReintentarTicket(nroTicket)
}

interface ServicioObrasSociales {
    + validarAfiliacion(obraSocialNombre, numAfiliado)
    + verificarRecetaElectronica(nroReceta)
    + registrarRecetaEnVenta(nroReceta, nroVta)
    + aplicarCoberturaVenta(nroVta, obraSocialNombre, numAfiliado)
}

interface ServicioPagos {
    + crearPago(nroVta, tipoPago, monto, cuotas)
    + iniciarTransaccion(nroVta, numTransacción)
    + procesarRespuesta(numTransacción, estadoPago)
    + confirmarPago(nroVta, numTransacción)
    + obtenerEstadoPago(numTransacción)
    + retryTransaccion(numTransacción)
    + registrarTransaccion(nroVta, numTransacción, estadoPago)
    + validarMediosAceptados(nroVta, tipoPago, monto)
}


' ----------------- ASOCIACIONES -----------------
NegocioControlador -- Venta
NegocioControlador -- Medicamento
NegocioControlador -- Cliente
NegocioControlador -- Usuario
NegocioControlador -- Drogueria
NegocioControlador ..> ServicioPedidos
NegocioControlador ..> ServicioObrasSociales
NegocioControlador ..> ServicioPagos


ServicioPagos -- Pago

ServicioPedidos -- Drogueria
ServicioPedidos -- Pedido
ServicioPedidos -- DetallePedido
ServicioPedidos -- Ticket
ServicioPedidos -- Venta

ServicioObrasSociales -- ObraSocial
ServicioObrasSociales -- Cobertura
ServicioObrasSociales -- Receta
ServicioObrasSociales -- Venta
ServicioObrasSociales -- Cliente

@enduml
