@startuml
title Eliminación de Proveedor (Droguería)

hide footbox

actor "Administrador: Admin" as admin
participant "NegocioControlador: Interfaz" as NegCtrl
participant "List<Drogueria>: droguerias" as listaDrogs
participant "Drogueria: objDrog" as drog
participant "List<Medicamento>: medicamentos" as listaMeds
participant "Medicamento: m" as med

admin -> NegCtrl : eliminarDrogueria(nombre: String)
activate NegCtrl

    NegCtrl -> listaDrogs : buscarDrogueria(nombre)
    activate listaDrogs
    
    loop [para cada d en droguerias]
        listaDrogs -> drog : getNombre()
        activate drog
        drog --> listaDrogs : << nombreActual >>
        deactivate drog
        
        alt nombre == nombreActual
            listaDrogs --> NegCtrl : << objDrog : Drogueria >>
            break
        end
    end
    
    listaDrogs --> NegCtrl : << NULL >>
    deactivate listaDrogs


    alt objDrog == NULL
        NegCtrl --> admin : << Error: El proveedor no existe >>
        
    else proveedor encontrado (EL ELSE PROTECTOR)
    

        NegCtrl -> listaMeds : verificarProductosAsociados(nombre)
        activate listaMeds
        
        loop [para cada m en medicamentos]
            listaMeds -> med : getDrogueriaNombre()
            activate med
            med --> listaMeds : << drogueriaAsociada : String >>
            deactivate med
            
            alt drogueriaAsociada == nombre
                listaMeds --> NegCtrl : << CONFLICTO >>
                break
            end
        end
        
        listaMeds --> NegCtrl : << OK >>
        deactivate listaMeds


        alt Se recibió CONFLICTO
            NegCtrl --> admin : << Error: Existen productos asociados >>
            
        else Se recibió OK (Éxito)
            
            NegCtrl -> listaDrogs : quitarDrogueria(objDrog)
            activate listaDrogs
            listaDrogs --> NegCtrl : << TRUE >>
            deactivate listaDrogs
            
            NegCtrl --> admin : << Éxito: Proveedor eliminado >>
            
        end
        
    end ' Fin del Else Protector

deactivate NegCtrl
@enduml