@startuml
!pragma teoz true
hide footbox
title Eliminación de Proveedores

actor "admin:Administrador" as admin
participant "gc:FarmaciaControlador" as gc
participant "catProv:<<Singleton>>\nCatalogoProveedores" as catProv
participant "listaProv[i]:Drogueria" as arrayProv
participant "catMed:<<Singleton>>\nCatalogoMedicamentos" as catMed
participant "listaMed[j]:Medicamento" as arrayMed
collections "«multiobjeto»\nlistaProv: List<Drogueria>" as lista_drog

admin -> gc : bajaDrogueria(CUIT : String)
activate gc

gc -> catProv : buscarProveedor(CUIT : String)
activate catProv

loop Para cada Drogueria en listaProv
    catProv -> arrayProv : getCUIT()
    activate arrayProv
    arrayProv --> catProv : <<CUITactual : String>>
    deactivate arrayProv
end

catProv --> gc : <<DrogEncontrada : Drogueria>>

deactivate catProv

alt No se pudo encontrar la Droguería
    gc --> admin : "Error: El proveedor no existe"
else Se encontró la Droguería

    gc -> catMed : tieneProductosAsociados(CUIT : String)
    activate catMed
    
    loop para cada Medicamento en listaMedicamentos
        catMed -> arrayMed : getProveedorCUIT()
        activate arrayMed
        arrayMed --> catMed : << cuitMed : String >>
        deactivate arrayMed
    end
    
    catMed --> gc : << tieneProductos : Bool >>
    deactivate catMed
    
    alt tieneProductos == TRUE
        gc --> admin : "Error: No se puede eliminar. Tiene productos asociados."
    else
        gc -> catProv : eliminarProveedor(DrogEncontrada : Drogueria)
        activate catProv
        catProv -> lista_drog : delete(DrogEncontrada : Drogueria)
        activate lista_drog
        lista_drog --> catProv : <<NULL>>
        deactivate lista_drog
        catProv --> gc : <<NULL>>
        deactivate catProv
        gc --> admin : "Proveedor eliminado exitosamente"
        deactivate gc
    end
end
@enduml