@startuml
title Modificación de Medicamento

hide footbox

actor "Administrador: Admin" as admin
participant "NegocioControlador: Interfaz" as NegCtrl
participant "List<Medicamento>: medicamentos" as listaMeds
participant "Medicamento: objMed" as med

admin -> NegCtrl : modificarMedicamento(codigoBarra: String, nombre: String, precio: Float, stock: Int, stockMin: Int, drogueria: String)
activate NegCtrl

    alt datos inválidos (precio < 0, nombre vacío, etc.)
        NegCtrl --> admin : << NULL >>
    else datos válidos
        
        NegCtrl -> listaMeds : buscarMedicamento(codigoBarra: String)
        activate listaMeds
        
        loop [para cada m en medicamentos]
            listaMeds -> med : getCodigoBarra()
            activate med
            med --> listaMeds : << codigoActual : String >>
            deactivate med
            
            alt codigoBarra == codigoActual
                listaMeds --> NegCtrl : << objMed : Medicamento >>
            end
        end
        deactivate listaMeds

        alt medicamento encontrado
            
            NegCtrl -> med : setNombre(nombre)
            activate med
            med --> NegCtrl : <<NULL>>
            deactivate med

            NegCtrl -> med : setPrecioUnitario(precio)
            activate med
            med --> NegCtrl : <<NULL>>
            deactivate med
            
            NegCtrl -> med : setStock(stock)
            activate med
            med --> NegCtrl : <<NULL>>
            deactivate med

            NegCtrl -> med : setStockMinimo(stockMin)
            activate med
            med --> NegCtrl : <<NULL>>
            deactivate med

            NegCtrl -> med : setDrogueria(drogueria)
            activate med
            med --> NegCtrl : <<NULL>>
            deactivate med
            
            NegCtrl --> admin : << NULL >>

        else medicamento no encontrado
            NegCtrl --> admin : << NULL >>
        end

    end

deactivate NegCtrl
@enduml