@startuml
!pragma teoz true
hide footbox
title Modificación de Medicamentos

actor "Administrador:Admin" as admin
participant "gc:GestionControlador" as gc
participant "catMed:<<Singleton>>\nCatalogoMedicamentos" as catMed
participant "listaMed[i]:Medicamento" as arrayMed
participant "medEncontrado:Medicamento" as medObj

admin -> gc : modificarMedicamento(codBarra: int, precio: float, stock: int, stockMin: int)
activate gc

gc -> catMed : buscarMedicamento(codBarra: int)
activate catMed

loop hasta codActual == codBarra
    catMed -> arrayMed : getCodigoBarra()
    activate arrayMed
    arrayMed --> catMed : <<codActual : int>>
    
    note right of arrayMed : Si no se encuentra, retornar null
    
    deactivate arrayMed
end
    
catMed --> gc : <<medEncontrado : Object Type : Medicamento>>
deactivate catMed

alt medEncontrado == null
    
    gc --> admin : "Error: El medicamento no existe"

else medEncontrado != null
    
    gc -> medObj : setPrecioUnitario(precio : float)
    activate medObj
    medObj --> gc : <<null>>
    deactivate medObj
    
    gc -> medObj : setStock(stock : int)
    activate medObj
    medObj --> gc : <<null>>
    deactivate medObj
    
    gc -> medObj : setStockMinimo(stockMin : int)
    activate medObj
    medObj --> gc : <<null>>
    deactivate medObj
    
    gc --> admin : "Éxito: Medicamento modificado correctamente."

end

deactivate gc
@enduml