@startuml
!pragma teoz true
hide footbox
title Modificación de Medicamentos

actor "Administrador:Admin" as admin
participant "gc:FarmaciaControlador" as gc
participant "catMed:<<Singleton>>\nCatalogoMedicamentos" as catMed
participant "listaMed[i]:Medicamento" as arrayMed
participant "medEncontrado:Medicamento" as medObj

admin -> gc : modificarMedicamento(codBarra: int, precio: float, stock: int, stockMin: int)
activate gc

gc -> catMed : buscarMedicamento(codBarra: int)
activate catMed

loop Para cada Medicamento en listaMed
    catMed -> arrayMed : getCodigoBarra()
    activate arrayMed
    arrayMed --> catMed : <<codActual : int>>
    
    deactivate arrayMed
end
    
catMed --> gc : <<medEncontrado : Medicamento>>
deactivate catMed

alt No se encontró el medicamento
    
    gc --> admin : "Error: El medicamento no existe"

else Se encontró el Medicamento
    
    gc -> medObj : setPrecioUnitario(precio : float)
    activate medObj
    medObj --> gc : <<null>>
    deactivate medObj
    
    gc -> medObj : setStock(stock : int)
    activate medObj
    medObj --> gc : <<null>>
    deactivate medObj
    
    gc -> medObj : setStockMinimo(stockMin : int)
    activate medObj
    medObj --> gc : <<null>>
    deactivate medObj
    
    gc --> admin : "Éxito: Medicamento modificado correctamente."
    deactivate gc

end

@enduml