@startuml
title Registro de Asistencia

hide footbox

actor "Administrador:Admin" as admin
participant "gc:FarmaciaControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoUsuarios" as cat
participant "listaUsu[i]:Usuario" as item
participant "catAsis:<<Singleton>>\nCatalogoAsistencias" as cat_asis
collections "<<multiobjeto>>\nlistaAsis:List" as lista_asis

admin -> ctrl : registrarAsistencia(legajo: String, fecha: Date, horaEnt: datetime, horaSal: datetime, estado: String)
activate ctrl

ctrl -> cat : buscarUsuario(legajo : String)
activate cat
    
loop para cada Usuario en ListaUsu
    cat -> item : getLegajo()
    activate item
    item --> cat : <<legajoActual : INT>>
        
    deactivate item
    end
    
    cat --> ctrl : << usuEncontrado : Usuario >>
    deactivate cat
    
alt Se encontró al Empleado
        
    create participant "nuevaAsis:Asistencia" as nueva_asis
    ctrl -> nueva_asis : CrearAsistencia(usuEncontrado : Usuario, fecha: Date, horaEnt: datetime, horaSal: datetime, estado: String)
    activate nueva_asis
    nueva_asis --> ctrl : <<nuevaAsis : Asistencia>>
    deactivate nueva_asis

    ctrl -> cat_asis : agregarAsistencia(nuevaAsis : Asistencia)
    activate cat_asis
        
    cat_asis -> lista_asis : add(nuevaAsis : Asistencia)
    activate lista_asis
    lista_asis --> cat_asis : <<null>>
    deactivate lista_asis
        
    cat_asis --> ctrl : <<null>> 
    deactivate cat_asis
        
    ctrl --> admin : "Éxito: Asistencia registrada"

else No se pudo encontrar al Empleado
    ctrl --> admin : "Error: Empleado no encontrado"
    deactivate ctrl
end
@enduml