@startuml
title Registro de Asistencia

hide footbox

actor "Administrador:Admin" as admin
participant "gc:GestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoUsuarios" as cat
participant "listaUsu[i]:Usuario" as item
participant "catAsis:<<Singleton>>\nCatalogoAsistencias" as cat_asis

admin -> ctrl : registrarAsistencia(legajo: String, fecha: Date, horaEnt: datetime, horaSal: datetime, estado: String)
activate ctrl

alt datos incompletos
    ctrl --> admin : "Error: Complete todos los campos"
else datosCompletos
    
    ctrl -> cat : buscarUsuario(legajo)
    activate cat
    
    loop [para cada u en usuarios]
        cat -> item : getLegajo()
        activate item
        item --> cat : legajoActual
        deactivate item
    end
    
    cat --> ctrl : usuEncontrado
    deactivate cat
    
    alt usuEncontrado != null
        
        create participant "nuevaAsis:Asistencia" as nueva_asis
        ctrl -> nueva_asis : CrearAsistencia(legajo: String, fecha: Date, horaEnt: datetime, horaSal: datetime, estado: String)
        activate nueva_asis
        nueva_asis --> ctrl : nuevaAsis
        deactivate nueva_asis

        ctrl -> cat_asis : agregarAsistencia(nuevaAsis)
        activate cat_asis
        cat_asis --> ctrl : << null >> 
        deactivate cat_asis
        
        ctrl --> admin : "Éxito: Asistencia registrada"

    else usuEncontrado == null
        ctrl --> admin : "Error: Empleado no encontrado"
    end
end

deactivate ctrl
@enduml