@startuml
title Carga de nuevos empleados

hide footbox

actor "Administrador:Admin" as admin
participant "gc:GestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoUsuarios" as cat
participant "usuActual:Usuario" as usu_actual

admin -> ctrl : registrarEmpleado(nombreUsuario: String, contraseña: String, tipoUsuario: String)
activate ctrl

ctrl -> cat : buscarUsuario(nombreUsuario)
activate cat

loop [para cada u en usuarios]
    cat -> usu_actual : getNombreUsuario()
    activate usu_actual
    usu_actual --> cat : << nombreActual : String >>
    deactivate usu_actual
    
    alt nombreUsuario == nombreActual
        cat --> ctrl : << u : Usuario >>
        deactivate cat
        ctrl --> admin : << "Error: Usuario ya registrado" >>

    else nombreUsuario != nombreActual
        deactivate cat
        
        create participant "nuevoUsu:Usuario" as nuevo_usu
        ctrl -> nuevo_usu : CrearUsuario(nombreUsuario: String, contraseña: String, tipoUsuario: String)
        activate nuevo_usu
        nuevo_usu --> ctrl : << nuevoUsu : Usuario >>
        deactivate nuevo_usu

        ctrl -> cat : agregarUsuario(nuevoUsu)
        activate cat
        cat --> ctrl : << null >>
        deactivate cat
        
        ctrl --> admin : << "Éxito: Empleado/Usuario registrado" >>
    end
end

deactivate ctrl
@enduml