@startuml DER
left to right direction

class TipoActor {
    - nombre
    - email
    - CUIT/CUIL
    - númTel
    - dirección
    - categoria

    + CargarActor(nombre, email, númTel, dirección, categoria)
    + ModificarActor(CUIT/CUIL, nombre, email, númTel, dirección, categoria)
    + EliminarActor(CUIT/CUIL)
    + BuscarActor(nombre, email, numTél, CUIT/CUIL)
}

class Persona {
    - DNI
}
class Establecimiento{
}

class DatosFarmacia{

}

class DatosLaboratorio{
    
}

class Pago{
    - cuotas
    - montoTotal
    - Descuento
}

enum TipoPago{
    Efectivo
    Transferencia
    Tarjeta
    Billetera Virtual
}

class Empleado {
    
}

class Usuario {
    - nombreUsuario
    - contraseña
    - IniciarSesión(nombreUsuario, contraseña)
}

enum TipoUsuario{
    Administrador
    Farmacéutico
}

class Cliente {
    - SaldoCtaCorriente
    + AñadirSaldo(cantidad)
    + restarSaldo(cantidad)
}
class ObraSocial {
    - NombreObraSocial
}

class Cobertura {
    - numAfiliado
    - Descuento
}

class Venta {
    - fechaVta
    - fechaVenta
    + RegistrarVenta(DatosCliente, tipoVta, tipoPago, montoTotal, cuotas)
    + BuscarVenta(nroVta)
    + ModificarVenta(nroVta, DatosCliente, tipoVta, tipoPago, montoTotal, cuotas)
    + EliminarVenta(nroVta)
    + ElegirTipoVenta(tipoVta)
    + CalcularMontoTotal(DetalleVta, Descuento)
}

class TipoDescuento{
    - motivo
    - porcentaje
    - fechainicio
    - fechaFinal
    - estado
    + AgregarPromoción(motivo, porcentaje, fechainicio, fechaFinal, estado)
    - EliminarPromoción(motivo)
    - ModificarPromoción(motivo, porcentaje, fechainicio, fechaFinal, estado)
}

enum TipoVenta{
    conReceta
    sinReceta
}

class DetalleVenta {
    - precio
    + AgregarProducto(Medicamento)
    + EliminarProducto(Medicamento)
    + aplicarDescuento(TipoDescuento)
    + calcularSubtotal()
}
class Medicamento {
    - codBarra
    - descripción
    - precioMedUnitario
    - stock
    + ConsultarStock(codBarra, descripción)
    + ActualizarPrecio(codBarra, nuevoPrecio)
    + ActualizarStock(codBarra, cantidadVendida)
    + DisminuirStock(int cantidad);
    + AumentarStock(int cantidad);
}
class Asistencia {
    - fecha
    - horaEntrada
    - horaSalida
    + RegistrarAsistencia(Empleado, horaEntrada, horaSalida, estado)
    + ObtenerHistorialAsistencia(desde, hasta);
}

enum estado {
    Licencia
    Ausente
    Presente
}

class Ticket {
    - nroTicket
    - fechaHora
    + GenerarTicket(DatosFarmacia, DatosCliente, fechaHora)
}

class Medico {
    - matriculaMed
}

class Receta {
    - nroReceta
    - fechaPrescripción
    - matriculaMedico
    + ObtenerReceta(nroReceta, numAfiliado)
}

class DetalleReceta{
    - fechaPrescripción
    - matriculaMedico
    - productosRecetados
}


class DetallePedido {
    - numPedido
    - nombreMed
    - montoFinal
    - precio
    + GenerarDetalle(numPedido, nombreMed, montoFinal, precio)
}

Usuario -- TipoUsuario

Asistencia -- estado

TipoActor -- Persona
TipoActor -- Establecimiento

Pago -- TipoPago

Cliente -- Cobertura

ObraSocial -- Cobertura

Cliente -- ObraSocial

Receta -- ObraSocial

Venta -- Ticket

Empleado -- Asistencia

TipoDescuento -- Cobertura

Venta -- Receta

Receta -- Medico

Medicamento -- DetalleVenta

DetalleReceta -- Medicamento

' SUPERCLASES

Persona --> Empleado

Persona --> Cliente

Empleado --> Usuario

Persona --> Medico

Establecimiento --> DatosLaboratorio

Establecimiento --> DatosFarmacia

DatosFarmacia --> Ticket

DatosLaboratorio --> DetallePedido

Venta ..> TipoVenta

' COMPOSICIONES

Receta *-- DetalleReceta

Venta *-- DetalleVenta

Cliente *-- Venta

Venta *-- Pago

Venta *-- TipoDescuento


@enduml