@startuml
title Carga de clientes frecuentes 

hide footbox

actor "Administrador:Admin" as admin
participant "gc:GestionControlador" as ctrl
participant "cat:<<Singleton>>\nCatalogoClientes" as cat
participant "clienteActual:Cliente" as cliente_actual

admin -> ctrl : registrarCliente(dni: String)
activate ctrl

ctrl -> cat : buscarCliente(dni)
activate cat

loop [para cada c en clientes]
    cat -> cliente_actual : getDni()
    activate cliente_actual
    cliente_actual --> cat : << dniActual : String >>
    deactivate cliente_actual
    
    alt dni == dniActual
        cat --> ctrl : << c : Cliente >>
        deactivate cat
        
        ctrl -> cliente_actual : getMontoAcumulado()
        activate cliente_actual
        cliente_actual --> ctrl : << monto : Float >>
        deactivate cliente_actual
        
        alt monto >= 400000
            ctrl -> cliente_actual : setEsFrecuente(true)
            activate cliente_actual
            cliente_actual --> ctrl : << null >> 
            deactivate cliente_actual
            
            ctrl --> admin : << "Éxito: Cliente actualizado a Frecuente" >>
            
        else monto < 400000
            ctrl --> admin : << "Error: No cumple con el monto ($400.000)" >>
        end

    else dni != dniActual
        deactivate cat
        ctrl --> admin : << "Error: Cliente no registrado" >>
    end
end

deactivate ctrl
@enduml