@startuml
!pragma teoz true
hide footbox
title Inicio de Sesión

actor "user:Usuario" as user
participant "cu:ControladorUsuario" as cu
participant "catUsu:<<Singleton>>\nCatalogoUsuarios" as catUsu
participant "listaUsuarios[i]:Usuario" as arrayUsu

user -> cu : iniciarSesion(nombreUsuario : String, contraseña : String)
activate cu

    
cu -> catUsu : autenticarUsuario(nombreUsuario : String, contraseña : String)
activate catUsu

loop Para cada Usuario en listaUsuarios
    catUsu -> arrayUsu : getNombreUsuario()
    activate arrayUsu
    arrayUsu --> catUsu : <<nomUsuario : String>>
    deactivate arrayUsu
    catUsu -> arrayUsu : getContraseña()
    activate arrayUsu
    arrayUsu --> catUsu : <<contraUsuario : String>>
    deactivate arrayUsu
    alt nombreUsuario = nomUsuario && contraseña = contraUsuario
        note over of catUsu: Respuesta = true
    else No se encontró al llegar al final de la lista o los datos no coinciden
        note over of catUsu: Respuesta = false
    end
end
    
catUsu --> cu : <<Respuesta : Bool>>
deactivate catUsu
    
alt No se encontró al Usuario (Respuesta == false)
    ' Camino Alternativo 3.a (Credenciales incorrectas)
    cu --> user : <<"Error: Credenciales incorrectas">>
else Se encontró al Usuario (Respuesta == true)
    ' Escenario de Éxito: Acceso concedido
    cu --> user : <<"Acceso concedido">>
    deactivate cu
end

@enduml