@startuml
!pragma teoz true
hide footbox
title Inicio de Sesión

actor "user:Usuario" as user
participant "cu:ControladorUsuario" as cu
participant "catUsu:<<Singleton>>\nCatalogoUsuarios" as catUsu
participant "listaUsuarios[i]:Usuario" as arrayUsu

user -> cu : iniciarSesion(nombreUsuario : String, contraseña : String)
activate cu

alt nombreUsuario es vacío O contraseña es vacía
    cu --> user : "Error: Debe completar todos los campos"
else
    ' El controlador delega la búsqueda al catálogo usando el método definido en V5.1
    
    cu -> catUsu : autenticarUsuario(nombreUsuario : String, contraseña : String)
    activate catUsu

    loop para cada u en listaUsuarios
        ' 1. Pedimos el nombre al objeto en la posición i
        catUsu -> arrayUsu : getNombreUsuario()
        activate arrayUsu
        arrayUsu --> catUsu : <<nomUsuario : String>>
        deactivate arrayUsu
        
        ' 2. Comparamos nombres
        alt nomUsuario == nombreUsuario
            ' 3. Si el nombre coincide, pedimos la contraseña
            catUsu -> arrayUsu : getContraseña()
            activate arrayUsu
            arrayUsu --> catUsu : <<contraUsuario : String>>
            deactivate arrayUsu
            
            alt contraUsuario == contraseña
                note right of catUsu
                    usuarioEncontrado = listaUsuarios[i]
                end note
                ' Si todo coincide, retornamos el usuario y cortamos
                catUsu --> cu : <<usuarioEncontrado : Object Type : Usuario>>
                break
            end
        end
    end
    
    catUsu --> cu : <<response : bool>>
    deactivate catUsu
    
    alt response == false
        ' Camino Alternativo 3.a (Credenciales incorrectas)
        cu --> user : <<"Error: Credenciales incorrectas">>
    else
        ' Escenario de Éxito: Acceso concedido
        cu --> user : <<"Acceso concedido">>
    end
end

deactivate cu
@enduml